"""Initial migration from restored database

Revision ID: 1bb25f7546f4
Revises: b0b8c4b409b3
Create Date: 2025-07-25 10:46:43.800483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1bb25f7546f4'
down_revision: Union[str, Sequence[str], None] = 'b0b8c4b409b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rework_data', sa.Column('repository_id', mssql.UNIQUEIDENTIFIER(), nullable=True))
    op.alter_column('rework_data', 'createdAtDate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_foreign_key(None, 'rework_data', 'repositories', ['repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rework_data', type_='foreignkey')
    op.alter_column('rework_data', 'createdAtDate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.drop_column('rework_data', 'repository_id')
    # ### end Alembic commands ###
